# Generated by Django 5.2.18 on 2026-10-06 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CUIT', 'CUIT'), ('CUIL', 'CUIL'), ('PASAPORTE', 'Pasaporte'), ('CONSUMIDOR_FINAL', 'Consumidor Final')], default='DNI', max_length=30)),
                ('numero_documento', models.CharField(blank=True, max_length=20)),
                ('condicion_fiscal', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('localidad', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FA', 'Factura A'), ('FB', 'Factura B'), ('FC', 'Factura C'), ('NCA', 'Nota de Crédito A'), ('NCB', 'Nota de Crédito B'), ('NCC', 'Nota de Crédito C'), ('NDA', 'Nota de Débito A'), ('NDB', 'Nota de Débito B'), ('NDC', 'Nota de Débito C')], max_length=3)),
                ('numero', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('cuit_emisor', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20)),
                ('importe_neto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('importe_iva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('importe_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cae', models.CharField(blank=True, max_length=20)),
                ('cae_vencimiento', models.DateField(blank=True, null=True)),
                ('numero_comprobante_asociado', models.PositiveIntegerField(blank=True, null=True)),
                ('respuesta_arca', models.JSONField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='billing.cliente')),
            ],
            options={
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='ComprobanteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=15)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=15)),
                ('alicuota_iva', models.DecimalField(decimal_places=2, default=21, max_digits=5)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.comprobante')),
            ],
        ),
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['numero'],
                'constraints': [models.UniqueConstraint(fields=('numero',), name='unique_punto_venta')],
            },
        ),
        migrations.AddField(
            model_name='comprobante',
            name='punto_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='billing.puntoventa'),
        ),
        migrations.AddConstraint(
            model_name='comprobante',
            constraint=models.UniqueConstraint(fields=('tipo', 'punto_venta', 'numero'), name='unique_comprobante'),
        ),
    ]
