# Generated by Django 5.2.18 on 2026-10-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoventa',
            name='habilitado_arca',
            field=models.BooleanField(default=False),
        ),
    ]
