# Generated by Django 5.2.18 on 2026-10-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_puntoventa_habilitado_arca'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonotributoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=1, unique=True)),
                ('ingresos_brutos_anuales', models.DecimalField(decimal_places=2, max_digits=15)),
                ('superficie_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('energia_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('alquileres_maximos', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('precio_unitario_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vigente_desde', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
