# Generated by Django 5.2.18 on 2026-10-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_monotributocategoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonotributoCategoria',
        ),
    ]
