# Generated by Django 5.2.18 on 2026-10-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_delete_monotributocategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='condicion_fiscal',
            field=models.CharField(blank=True, choices=[('Responsable Inscripto', 'Responsable Inscripto'), ('Monotributo', 'Monotributo'), ('Exento', 'IVA Exento'), ('Consumidor Final', 'Consumidor Final'), ('No Responsable', 'No Responsable'), ('Sujeto No Categorizado', 'Sujeto No Categorizado')], max_length=50),
        ),
    ]
