# Generated by Django 5.2.18 on 2026-10-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonotributoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('A', 'Categoría A'), ('B', 'Categoría B'), ('C', 'Categoría C'), ('D', 'Categoría D'), ('E', 'Categoría E'), ('F', 'Categoría F'), ('G', 'Categoría G'), ('H', 'Categoría H'), ('I', 'Categoría I'), ('J', 'Categoría J'), ('K', 'Categoría K')], max_length=1, unique=True)),
                ('ingresos_brutos_anuales', models.DecimalField(decimal_places=2, max_digits=15)),
                ('superficie_maxima_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('energia_maxima_kw', models.PositiveIntegerField()),
                ('alquileres_maximos_anuales', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio_unitario_maximo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vigente_desde', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Monotributo',
                'verbose_name_plural': 'Categorías de Monotributo',
                'ordering': ['categoria', '-vigente_desde'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='categoria_monotributo',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K')], max_length=1),
        ),
    ]
