# Generated by Django 5.2.18 on 2026-10-09 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_monotributocategoria_tenant_categoria_monotributo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='categoria_monotributo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='tenant.monotributocategoria', verbose_name='Categoría de Monotributo'),
        ),
    ]
