# Generated by Django 5.2.18 on 2026-10-06 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArcaConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('DELEGACION', 'Delegación a FacturAR'), ('PROPIO', 'Certificado propio')], default='DELEGACION', max_length=20)),
                ('ambiente', models.CharField(choices=[('HOMOLOGACION', 'Homologación'), ('PRODUCCION', 'Producción')], default='HOMOLOGACION', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArcaToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=100)),
                ('token', models.TextField()),
                ('sign', models.TextField()),
                ('expiracion', models.DateTimeField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArcaDelegacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit_cliente', models.CharField(max_length=20)),
                ('cuit_facturar', models.CharField(max_length=20)),
                ('servicio', models.CharField(default='wsfe', max_length=100)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVA', 'Activa'), ('REVOCADA', 'Revocada'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('fecha_delegacion', models.DateTimeField(blank=True, null=True)),
                ('ultima_verificacion', models.DateTimeField(blank=True, null=True)),
                ('mensaje', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('configuracion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delegacion', to='arca_gateway.arcaconfiguracion')),
            ],
        ),
    ]
