# Generated by Django 5.2.18 on 2026-10-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arca_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcatoken',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='arcatoken',
            name='ambiente',
            field=models.CharField(choices=[('HOMOLOGACION', 'Homologación'), ('PRODUCCION', 'Producción')], default='HOMOLOGACION', max_length=20),
        ),
    ]
